# Generated by Django 3.2.4 on 2021-06-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210624_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
