# Generated by Django 3.2.4 on 2021-06-24 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_rename_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='like',
            name='who_liked',
        ),
        migrations.AddField(
            model_name='like',
            name='who_liked',
            field=models.ManyToManyField(through='api.Article', to=settings.AUTH_USER_MODEL),
        ),
    ]
