# Generated by Django 3.2.4 on 2021-06-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_article_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
    ]
