# Generated by Django 3.2.4 on 2021-06-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_article_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
    ]
