# Generated by Django 3.2.4 on 2021-06-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published']},
        ),
    ]
