# Generated by Django 3.2.4 on 2021-06-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
