# Generated by Django 3.2.4 on 2021-06-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
