# Generated by Django 3.2.4 on 2021-08-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='web_uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
