# Generated by Django 3.2.4 on 2021-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_article_web_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='web_uri',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
