# Generated by Django 3.2.4 on 2021-08-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
    ]
